{
 "title": "Bank API - Observability",
 "tags": [
  "bank-api",
  "observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "tx", "label": "Transaction ID" },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": {}
   },
   {
    "name": "level_json",
    "label": "Level_json",
    "query": {}
   },
   {
    "name": "level_txt",
    "label": "Level_txt",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Tempo- All",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "limit": 20, "query": "{ }", "tableType": "traces" }
   ]
  },
  { "title": "Latencia p50 / p95 / p99", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Tempo- Transactions api",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "limit": 20, "query": "{ }", "tableType": "traces" },
    {
     "limit": 20,
     "query": "{ resource.service.name = \"bank-transactions-api\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": ".NET Runtime - GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_gc_collections_count_total[5m])\r\nor\r\nrate(dotnet_gc_collections_total[5m])\r\n",
     "legendFormat": "Gen {{generation}}"
    }
   ]
  },
  {
   "title": "Total Requests por Status Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (http_server_request_duration_seconds_count)",
     "legendFormat": "HTTP {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Errores 5xx / minuto",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[1m])) * 60)\r\nor on() vector(0)",
     "legendFormat": "Errores 5xx/min"
    }
   ]
  },
  {
   "title": "Tasa de éxito (2xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_route=\"/api/transactions/transfer\", http_response_status_code=~\"2..\"}[5m]))\r\n/\r\nsum(rate(http_server_request_duration_seconds_count{http_route=\"/api/transactions/transfer\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count[1m])",
     "legendFormat": "{{http_request_method}} {{http_route}} ({{http_response_status_code}})"
    }
   ]
  },
  {
   "title": "Transferencias fallidas",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{container=~\".*bank.*\"} |= \"Transfer failed\""
    }
   ]
  },
  {
   "title": "Top endpoints más lentos (P95 por ruta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "topk(5,\r\n  histogram_quantile(\r\n    0.95,\r\n    sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le, http_route)\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transferencias fallidas y timeout",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "{container=~\".*bank.*\"} |= \"Transfer failed\" |= \"INTERBANK_TIMEOUT\""
    }
   ]
  },
  {
   "title": "RPS de transferencias",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_route=\"/api/transactions/transfer\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latencia P95 SOLO de transferencias",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(http_server_request_duration_seconds_bucket{http_route=\"/api/transactions/transfer\"}[5m])) by (le)\r\n)"
    }
   ]
  },
  {
   "title": "Tasa de fallo (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_route=\"/api/transactions/transfer\", http_response_status_code=~\"5..\"}[5m]))\r\n/\r\nsum(rate(http_server_request_duration_seconds_count{http_route=\"/api/transactions/transfer\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs en Vivo (Bank API)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{container=~\".*bank-api.*\"}"
    }
   ]
  }
 ]
}